### ISSUE TITLE
toolbox fails with "Failed to parse --bind(-ro)= argument : Invalid argument"

### ISSUE THREAD

**Issue by leopoldodonnell** [wallneradam/docker-coreos-toolbox-ubuntu#1]
Master branch (the only branch at this date)

1. Startup an AWS instance with: `CoreOS-stable-1185.5.0 (ami-b5e5e3a2)`
1. Log into the core account
1. Create/copy `.tooboxrc` with contents from this project
1. Run `toolbox`

Once the container has downloaded (and in subsequent invocations) you will receive the error:

    Failed to parse --bind(-ro)= argument : Invalid argument

**Comment by wallneradam** [comment]
Thanks for your report.
It is because the script tries to bind the ssh authentication socket as well into the container. But if you don't ssh with auth socket, that environment variable is missing. I've changed the script, so it can be started without the SSH_AUTH_SOCK variable. However it needed for all CoreOS's stuffs. So I suggest you to ssh with `ssh -A`.
